== Basics

Styx uses the Nix expression language.
The Nix expression language is a lazily evaluated functional language with uncommon semantics. +
It is recommended to read the link:http://nixos.org/nix/manual/#ch-expression-language[Nix expression language chapter] of the Nix manual to get more familiar with it.

=== Hello world!

Let's look at a very basic example of a styx site `site.nix` file. A real site
also needs a `flake.nix` that passes `pkgs`, `styxlib`, and `styxthemes` into
this function; the site template provides that wiring.

[source, nix]
.Hello world!
----
{
  pkgs,
  styxlib,
  styxthemes ? {},
  extraConf ? {},
}: rec { # <1>

  loaded = styxlib.themes.load { # <2>
    lib = styxlib;
    config = [ ./conf.nix extraConf ];
    themes = [ styxthemes.generic-templates ];
    env = { inherit data pages pkgs; };
  };

  inherit (loaded) conf files templates env lib; # <3>

  data = {};

  pages = {
    index = { # <4>
      title    = "Styx example page";
      content  = "<p>Hello world!</p>"; # <5>
      path     = "/index.html"; # <6>
      template = templates.page.full; # <7>
      layout   = templates.layout; # <8>
    };
  };

  pageList = lib.generation.pagesToList { inherit pages; };
  site = lib.generation.mkSite { inherit files pageList; }; # <9>

}
----

<1> `site.nix` is a function. Its arguments are supplied by the site's
    `flake.nix`: `pkgs` from nixpkgs, `styxlib` from the styx flake's `lib`
    output, and `styxthemes` from `styx.legacyPackages.<system>.styxthemes`.
<2> Themes and configuration are loaded with `styxlib.themes.load`.
<3> The loaded theme provides `conf`, `files`, `templates`, `env`, and `lib`.
<4> Pages are declared in the `pages` attribute set. Here `index` is the only
    page generated.
<5> Page content. Data loaders usually populate this attribute; here it is set
    inline.
<6> The URL path of the generated page.
<7> The page template from the loaded theme.
<8> The page layout from the loaded theme.
<9> `mkSite` turns the page list into a store path containing the static site.

Build and preview the site from the site directory:

[source, sh]
.Generating a preview of the "Hello world!" site
----
$ nix build
$ nix run .#serve
----


TIP: Even if this is a simple example, nix language semantics can be confusing. +
In a nutshell, to build a site, `mkSite` evaluates `page.layout (page.template page)` and output the result in `page.path` for every page in `pageList`. +
That is the reason `layout`, `template` and `path` are required attributes of a page set.

NOTE: Nix expression language is lazily evaluated, so infinite data structures are not a problem (unless some code tries to evaluate them).

=== Files

In its simplest form, styx just needs a `site.nix` and a `flake.nix` to generate a site like presented in the <<Hello world!>> example.

The `nix flake init -t github:styx-static/styx#default` template generates a few more files for convenience.

[source]
----
├── flake.nix   # <1>
├── conf.nix    # <2>
├── readme.md   # <3>
├── site.nix    # <4>
├── data/       # <5>
└── themes/     # <6>
----

<1> `flake.nix` wires `site.nix` into `packages`, `checks`, and `apps` (`serve`,
    `linkcheck`, `deploy-gh-pages`).
<2> `conf.nix` is the main configuration file, see <<Configuration>> for details.
<3> `readme.md` provides some basic information about how to start using styx.
<4> `site.nix` is the main file for site generation, see <<site.nix,site.nix>> for details.
<5> `data/` is an empty directory meant to hold site data.
<6> `themes/` is an empty directory meant to hold custom themes.

NOTE: The file structure of a styx site is totally free and can be changed according to needs. +
What matters is that your `flake.nix` imports `site.nix` with the correct arguments.


[[site.nix]]
=== site.nix

The `site.nix` used in the <<Hello world!>> example contains only enough code to generate a single page. A standard `site.nix` is usually more structured.

A complex example of a `site.nix` if the showcase theme example `site.nix` that uses almost every feature available.

A standard `site.nix` is divided in multiple sections, each section handling a particular topic. +
Standard sections are:

- <<site.nix-init,Init>>
- <<site.nix-themes,Themes>>
- <<site.nix-data,Data>>
- <<site.nix-pages,Pages>>
- <<site.nix-site,Site>>

[[site.nix-init]]
==== Init

This section is the basic setup of styx, it should not be changed and used as is for most setups.

[source, nix]
.Standard Init section
----
/*-----------------------------------------------------------------------------
   Init

   Initialization of Styx, should not be edited
-----------------------------------------------------------------------------*/

{
  pkgs,
  styxlib,
  styxthemes ? {},
  extraConf ? {},
}: rec {
----


[[site.nix-themes]]
==== Themes

The theme section is responsible for loading themes assets (configuration, library, static files, and templates).

Themes are detailed in the <<Themes>> section.

[source, nix]
.Standard themes section
----
  loaded = styxlib.themes.load { # <1>
    lib = styxlib;

    config = [ ./conf.nix extraConf ]; # <2>

    themes = [ # <3>
      styxthemes.generic-templates
      ./themes/my-theme
    ];

    env = { inherit data pages pkgs; }; # <4>
  };

  inherit (loaded) conf files templates env lib; # <5>
----

<1> Load themes and merge their configuration.
<2> `config` is a list of configuration sources. Items at the end have higher priority. +
    `extraConf` is typically passed from the site's `flake.nix` (for example to override `siteUrl` when serving locally).
<3> `themes` is a list so it is possible to set multiple themes at the same time to <<Combining Themes,combine them>>. Themes at the beginning of the list have a lower priority. +
Themes can be paths like `./themes/my-theme` or entries from the `styxthemes` set passed in by `flake.nix`.
<4> Extra variables to add to the template environment.
<5> Bring the loaded theme data into scope.

[[site.nix-data]]
==== Data

The data section is responsible for loading the data used in the site.

The <<Data>> section explains in detail how to manage data.

[source, nix]
.Standard data section
----
/*-----------------------------------------------------------------------------
   Data

   This section declares the data used by the site
-----------------------------------------------------------------------------*/

  data = {
    about = lib.data.loadFile { file = ./pages/about.md; inherit env; }; # <1>
  };
----

<1> Example of loading a Markdown file with the `loadFile` function.

[[site.nix-pages]]
==== Pages

The pages section is used to declare the pages that will be generated by `mkSite`. +
Even if `mkSite` expects a page list, it is usually declared as an attribute set for convenience.

There are multiple functions available to generate different type of pages, but a page is ultimately an attribute set with at least the `layout`, `template` and `path` attribute defined.

The <<Pages>> section explains in detail how to create pages.

[source, nix]
.Standard pages section
----
/*-----------------------------------------------------------------------------
   Pages

   This section declares the pages that will be generated
-----------------------------------------------------------------------------*/

  pages = {

    about = {
      path     = "/about.html";
      template = templates.page.full;
      layout   = templates.layout;
    } // data.about; # <1>

  };
----

<1> `//` is the operator to merge attribute sets, this merge the `data.about` data attribute set in the `pages.about` page attribute set.

IMPORTANT: `path` must start with a `/`.

[[site.nix-site]]
==== Site

This is the final part and shortest section of `site.nix`. This section consists of a call to link:library.html#lib.generation.mkSite[`mkSite`].

[source, nix]
.Standard mkSite section
----
/*-----------------------------------------------------------------------------
   Site

-----------------------------------------------------------------------------*/

  /* Converting the pages attribute set to a list
  */
  pageList = lib.generation.pagesToList { inherit pages; }; # <1>

  site = lib.generation.mkSite { inherit files pageList; }
}
----

<1> `mkSite` requires pages as a list, so `pagesToList` converts the pages attribute set to a list.

NOTE: `files` is generated in the theme section using enabled themes. +
`inherit` is a shorthand for writing sets, `{ inherit a; }` is equivalent to `{ a = a; }`.

==== site.nix in a nutshell

====
`site.nix` is a function:

- taking `pkgs`, `styxlib`, and optionally `styxthemes` and `extraConf`.
- returning an attribute set with a `site` attribute using the `lib.generation.mkSite` function.
====

====
`mkSite` is a function:

- taking at least a list of pages to generate as the `pageList` argument.
- evaluating each page set by evaluating `page.layout (page.template page)` and outputting the result in `page.path`.
- returning a generated static site directory.

NOTE: `mkSite` is a wrapper for nixpkgs `runCommand` function.
====

