== Deployment

=== GitHub pages

Styx sites can publish to GitHub Pages using the `deploy-gh-pages` app included
in the site template's `flake.nix`. It uses a git worktree so your main working
tree is left untouched.

==== First deployment

From your site repository (with a `flake.nix` that defines `apps.deploy-gh-pages`):

[source, sh]
----
$ nix run .#deploy-gh-pages
----

On the first run this will:

- create a `gh-pages` git worktree at `./gh-pages` (orphan branch if the branch
  does not exist yet)
- build the site and commit it to that branch

Add `gh-pages/` to `.gitignore` in your main branch if it is not already there.

==== Updating the gh-pages branch

Re-run the same command after changes:

[source, sh]
----
$ nix run .#deploy-gh-pages
----

Each run rebuilds the site and creates a new commit on the `gh-pages` branch in
the worktree. Push when ready:

[source, sh]
----
$ git -C gh-pages push -u origin gh-pages
----

NOTE: The deploy app never pushes automatically. You control when changes go
live.

=== NixOps

link:http://nixos.org/nixops/[NixOps] is a deployment tool for NixOS
configurations, and can be used to deploy styx sites.

[[nixops-example]]
[source, nix]
.NixOps expression to deploy a styx website
----
{
  network.description = "Styx example";

  webserver = { config, pkgs, ... }: { # <1>
    deployment = { # <2>
      targetEnv = "virtualbox";
      virtualbox.memorySize = 1024;
      virtualbox.headless = true;
    };

    networking.firewall.allowedTCPPorts = [ 80 ]; # <3>

    services.nginx = { # <4>
      enable = true;
      httpConfig = ''
        server {
          listen 80;
          location / {
            root ${(builtins.getFlake (toString ./.)).packages.${pkgs.system}.default}; # <5>
          }
        }
      '';
    };
  };
}
----

<1> Create a machine named `webserver` for deployment.
<2> Set up deployment information, for this example deploy on a VirtualBox machine.
<3> Open port 80 on the `webserver` machine.
<4> Nginx settings.
<5> Set the Nginx root to the site's `packages.default` output. This assumes the
    NixOps expression lives in the site repository next to `flake.nix`.

NOTE: The NixOps link:http://nixos.org/nixops/manual/[manual] provides information about all the deployment options.

Then the site can be deployed via NixOps with the following set of commands:

[source, sh]
----
$ nixops create -d styx-site nixops-expression.nix # <1>
$ nixops deploy -d styx-site # <2>
----

<1> This command creates a new NixOps deployment, the `-d` flag specify the deployment name. +
The deployment information can be queried with the `nixops info -d styx-site`. +
`nixops-expression.nix` is a file containing the nix expression for the deployment like the one showed in the <<nixops-example,example>>.
<2> This command will create the VirtualBox machine and deploy the configuration into it. +
If all goes well, the website will be available by opening the deployment machine in a browser.
The deployement machine IP can be found with the `nixops info -d styx-site`.


=== Amazon S3 Bucket

Amazon S3 buckets can be used to host static websites.
The AWS CLI tool can be used in conjunction with a built styx site to upload to a S3 bucket.

[source, sh]
.Deploying a styx website to S3
----
$ nix-shell -p awscli

$ aws s3 sync $(nix build --print-out-paths) s3://<bucket name>/
----

Build with a custom `siteUrl` by adjusting `conf.nix` or the `extraConf` passed
from `flake.nix` before running `nix build`.

NOTE: For a S3 website to be world accessible, link:http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteAccessPermissionsReqd.html[adjusting policies might be required].


=== Other

Styx does not yet provide a universal deployment method, but `rsync` can be used to deploy a Styx site to a remote server via ssh.

[source, sh]
----
$ nix build
$ rsync -av ./result/ user@server:/var/www/mysite/
----
